In [1]:
from selenium import webdriver
import pandas as pd
import numpy as np
import os

In [2]:
browser = webdriver.Chrome('chromedriver.exe')

In [3]:
url = 'https://www.imdb.com/india/top-rated-indian-movies/?pf_rd_m=A2FGELUUNOQJNL&pf_rd_p=600ca544-31f5-4bd8-ae38-ea4014c93bab&pf_rd_r=4PPKDSWRTY0P44HMBCJM&pf_rd_s=right-4&pf_rd_t=15061&pf_rd_i=homepage&ref_=hm_india_tr_rhs_1'

# Method 1: Using pd.read_html

In [4]:
table = pd.read_html(url)
len(table)

2

In [5]:
browser.get(url)

In [7]:
movies = table[0]

In [8]:
movies

,Unnamed: 0,Rank & Title,IMDb Rating,Your Rating,Unnamed: 4
0,NaN,1. Anand (1971),8.7,12345678910 NOT YET RELEASED Seen,NaN
1,NaN,2. Drishyam (2013),8.6,12345678910 NOT YET RELEASED Seen,NaN
2,NaN,3. Nayakan (1987),8.6,12345678910 NOT YET RELEASED Seen,NaN
3,NaN,4. Anbe Sivam (2003),8.5,12345678910 NOT YET RELEASED Seen,NaN
4,NaN,5. Gol Maal (1979),8.5,12345678910 NOT YET RELEASED Seen,NaN
5,NaN,6. Vikram Vedha (2017),8.5,12345678910 NOT YET RELEASED Seen,NaN
6,NaN,7. Black Friday (2004),8.5,12345678910 NOT YET RELEASED Seen,NaN
7,NaN,8. Ratsasan (2018),8.4,12345678910 NOT YET RELEASED Seen,NaN
8,NaN,9. Dangal (2016),8.4,12345678910 NOT YET RELEASED Seen,NaN
9,NaN,10. Pather Panchali (1955),8.4,12345678910 NOT YET RELEASED Seen,NaN
10,NaN,11. Uri: The Surgical Strike (2019),8.4,12345678910 NOT YET RELEASED Seen,NaN
11,NaN,12. Taare Zameen Par (2007),8.4,12345678910 NOT YET RELEASED Seen,NaN
12,NaN,13. Andhadhun (2018),8.4,12345678910 NOT YET RELEASED Seen,NaN
13,NaN,14. 3 Idiots (2009),8.4,12345678910 NOT YET RELEASED Seen,NaN
14,NaN,15. Aruvi (2016),8.3,12345678910 NOT YET RELEASED Seen,NaN
15,NaN,16. 96 (2018),8.3,12345678910 NOT YET RELEASED Seen,NaN
16,NaN,17. Manichithrathazhu (1993),8.3,12345678910 NOT YET RELEASED Seen,NaN
17,NaN,18. Jaane Bhi Do Yaaro (1983),8.3,12345678910 NOT YET RELEASED Seen,NaN
18,NaN,19. Thalapathi (1991),8.3,12345678910 NOT YET RELEASED Seen,NaN
19,NaN,20. Guide (1965),8.3,12345678910 NOT YET RELEASED Seen,NaN
20,NaN,21. Chupke Chupke (1975),8.3,12345678910 NOT YET RELEASED Seen,NaN
21,NaN,22. Thani Oruvan (2015),8.2,12345678910 NOT YET RELEASED Seen,NaN
22,NaN,23. Kannathil Muthamittal (2002),8.2,12345678910 NOT YET RELEASED Seen,NaN
23,NaN,24. Khosla Ka Ghosla! (2006),8.2,12345678910 NOT YET RELEASED Seen,NaN
24,NaN,25. Gully Boy (2019),8.2,12345678910 NOT YET RELEASED Seen,NaN
25,NaN,26. Apur Sansar (1959),8.2,12345678910 NOT YET RELEASED Seen,NaN
26,NaN,27. Vada Chennai (2018),8.2,12345678910 NOT YET RELEASED Seen,NaN
27,NaN,28. Dhuruvangal Pathinaaru (2016),8.2,12345678910 NOT YET RELEASED Seen,NaN
28,NaN,29. Peranbu (2018),8.2,12345678910 NOT YET RELEASED Seen,NaN
29,NaN,30. Shahid (2012),8.2,12345678910 NOT YET RELEASED Seen,NaN
...,...,...,...,...,...
220,NaN,221. Yuva (2004),7.4,12345678910 NOT YET RELEASED Seen,NaN
221,NaN,222. Petta (2019),7.4,12345678910 NOT YET RELEASED Seen,NaN
222,NaN,223. Golmaal: Fun Unlimited (2006),7.4,12345678910 NOT YET RELEASED Seen,NaN
223,NaN,224. Kaminey (2009),7.4,12345678910 NOT YET RELEASED Seen,NaN
224,NaN,225. Life in a Metro (2007),7.4,12345678910 NOT YET RELEASED Seen,NaN
225,NaN,226. Monsoon Wedding (2001),7.4,12345678910 NOT YET RELEASED Seen,NaN
226,NaN,227. Khiladi (1992),7.3,12345678910 NOT YET RELEASED Seen,NaN
227,NaN,228. Raid (2018),7.3,12345678910 NOT YET RELEASED Seen,NaN
228,NaN,229. Page 3 (2005),7.3,12345678910 NOT YET RELEASED Seen,NaN
229,NaN,230. Ghulam (1998),7.3,12345678910 NOT YET RELEASED Seen,NaN
230,NaN,231. Khaleja (2010),7.3,12345678910 NOT YET RELEASED Seen,NaN
231,NaN,232. Maine Pyar Kiya (1989),7.3,12345678910 NOT YET RELEASED Seen,NaN
232,NaN,233. Ishqiya (2010),7.3,12345678910 NOT YET RELEASED Seen,NaN
233,NaN,234. Raman Raghav 2.0 (2016),7.3,12345678910 NOT YET RELEASED Seen,NaN
234,NaN,235. Ghajini (2008),7.3,12345678910 NOT YET RELEASED Seen,NaN
235,NaN,236. Bharat Ane Nenu (2018),7.3,12345678910 NOT YET RELEASED Seen,NaN
236,NaN,237. Lootera (2013),7.3,12345678910 NOT YET RELEASED Seen,NaN
237,NaN,238. Srimanthudu (2015),7.3,12345678910 NOT YET RELEASED Seen,NaN
238,NaN,239. Bhool Bhulaiyaa (2007),7.3,12345678910 NOT YET RELEASED Seen,NaN
239,NaN,240. Holiday (2014),7.3,12345678910 NOT YET RELEASED Seen,NaN
240,NaN,241. Parineeta (2005),7.3,12345678910 NOT YET RELEASED Seen,NaN
241,NaN,242. Ayan (2009),7.3,12345678910 NOT YET RELEASED Seen,NaN
242,NaN,243. Gold (2018),7.3,12345678910 NOT YET RELEASED Seen,NaN
243,NaN,244. Mardaani (2014),7.3,12345678910 NOT YET RELEASED Seen,NaN
244,NaN,245. Saajan (1991),7.3,12345678910 NOT YET RELEASED Seen,NaN
245,NaN,246. Taxi No. 9 2 11: Nau Do Gyarah (2006),7.3,12345678910 NOT YET RELEASED Seen,NaN
246,NaN,247. Shaitan (2011),7.2,12345678910 NOT YET RELEASED Seen,NaN
247,NaN,248. Mom (2017),7.2,12345678910 NOT YET RELEASED Seen,NaN
248,NaN,249. Te3n (2016),7.2,12345678910 NOT YET RELEASED Seen,NaN
249,NaN,250. No One Killed Jessica (2011),7.2,12345678910 NOT YET RELEASED Seen,NaN

In [9]:
table[1]

,0,1,2,3,4,5,6,7
0,Amazon Affiliates,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Prime Video Unlimited Streamingof Movies & TV,Amazon UK Buy Movies onDVD & Blu-ray,Amazon Germany Buy Movies onDVD & Blu-ray,Amazon Italy Buy Movies onDVD & Blu-ray,Amazon France Buy Movies onDVD & Blu-ray,Amazon India Buy Movie andTV Show DVDs,DPReview DigitalPhotography,Audible DownloadAudio Books

# Method 2 : Using Selenium

In [10]:
sel = 'table.chart.full-width[data-caller-name="imdb-featured-india"]'
table_tag = browser.find_element_by_css_selector(sel)
table_tag

In [12]:
#Get Column Names

In [13]:
thead = table_tag.find_element_by_css_selector('thead')
tr = thead.find_element_by_css_selector('tr')
th_tags = tr.find_elements_by_css_selector('th')
len(th_tags)

5

In [14]:
th_tags = table_tag.find_elements_by_css_selector('thead > tr > th')
len(th_tags)

5

In [15]:
col_names = [th.text for th in th_tags]
col_names

['', 'Rank & Title', 'IMDb Rating', 'Your Rating', '']

# Get data

In [18]:
col_names = [th.text for th in th_tags]
col_names[0] = 'Poster'
col_names[-1] = 'Watchlist'
imdb =pd.DataFrame(columns=col_names)
tr_tags=table_tag.find_elements_by_css_selector('tbody > tr')

In [19]:
len(tr_tags)

250

In [22]:
for tr in tr_tags:
    td_tags = tr.find_elements_by_css_selector('td')
    #print(len(td_tags))
    td_data = [td.text for td in td_tags]
    row_series = pd.Series(td_data, index=col_names)
    imdb = imdb.append(row_series, ignore_index=True)

In [23]:
imdb.head()

  Poster          Rank & Title IMDb Rating Your Rating Watchlist
0              1. Anand (1971)         8.7
1           2. Drishyam (2013)         8.6
2            3. Nayakan (1987)         8.6
3         4. Anbe Sivam (2003)         8.5
4           5. Gol Maal (1979)         8.5

In [25]:
col_names = [th.text for th in th_tags]
col_names[0] = 'Poster'
col_names[-1] = 'Watchlist'
imdb =pd.DataFrame(columns=col_names)
tr_tags=table_tag.find_elements_by_css_selector('tbody > tr')

for tr in tr_tags:
    td_tags = tr.find_elements_by_css_selector('td')
    td_data = [td.text for td in td_tags]
    
    img_src = td_tags[0].find_element_by_css_selector('img')
    img_src = img_src.get_attribute('src')
    td_data[0] = img_src
    
    row_series = pd.Series(td_data, index=col_names)
    imdb = imdb.append(row_series, ignore_index=True)
imdb.head()

,Poster,Rank & Title,IMDb Rating,Your Rating,Watchlist
0,https://m.media-amazon.com/images/M/MV5BNmZkMT...,1. Anand (1971),8.7,,
1,https://m.media-amazon.com/images/M/MV5BYmY3Mz...,2. Drishyam (2013),8.6,,
2,https://m.media-amazon.com/images/M/MV5BZmFiYj...,3. Nayakan (1987),8.6,,
3,https://m.media-amazon.com/images/M/MV5BMjQwZW...,4. Anbe Sivam (2003),8.5,,
4,https://m.media-amazon.com/images/M/MV5BMjA4OT...,5. Gol Maal (1979),8.5,,

In [27]:
import glob  #to list out all the files in current working directory
glob.glob('*')

['1. Anand (1971)',
 '1. Anand (1971).jpg',
 'chromedriver.exe',
 'Data Scraping - Batch 6 - Day 1.html',
 'Data Scraping - Batch 6 - Day 2.ipynb',
 'Data Scraping - Batch 6 - Day 3.ipynb',
 'Data Scraping - Batch 6 - Day 4.ipynb',
 'Data Scraping - Day1.ipynb',
 'Data Scraping - Day2.ipynb',
 'Data Scraping - Day3.ipynb',
 'Data Scraping - Day4.ipynb',
 'Data Scraping - Day5.ipynb',
 'Data_Scraping_Movie_IMDB_Day_3.ipynb',
 'debug.log',
 'imdb_top250_indian_movies.csv',
 'index.html',
 'jobs_datascience.csv',
 'Medium_Scrapping.html',
 'movies_images',
 'narendramodi_tweets.csv',
 'narendramodi_tweets2.csv',
 'naukri_jobs.csv',
 'naukri_jobs_datascience.csv',
 'naukri_jobs_datascience.csv.zip',
 'oyo data scraping.txt',
 'Oyo Rooms Bengaluru Data Scraping.ipynb',
 'Save_article in file.ipynb',
 'Scraping Assignment.html',
 'Scraping Assignment.ipynb',
 'temp.csv',
 'tweets_datascience.csv',
 'twitter.py',
 'twitter_streaming.py',
 'untitled.txt',
 '__MACOSX']

In [28]:
#saving image from url
import urllib                            #library to retrieve url's
import os
img_url = imdb.loc[0, 'Poster']
movie_name = imdb.loc[0, 'Rank & Title']  
img_extn = img_url[img_url.rfind('.'):]
folder_name = 'movies_images_imdb'

if not folder_name in glob.glob('*'):     #checks whether folder name is existed or not
    os.makedirs(folder_name)
img_name = folder_name+ '/' + movie_name + img_extn


print(img_url, img_name)                        #movie_name
urllib.request.urlretrieve(img_url,img_name)    #movie_name

https://m.media-amazon.com/images/M/MV5BNmZkMTMzNmEtMWU5NC00MjEzLWE5MzktYzRlMmQyMzk0YmM1XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_UX45_CR0,0,45,67_AL_.jpg movies_images_imdb/1. Anand (1971).jpg

('movies_images_imdb/1. Anand (1971).jpg',
 <http.client.HTTPMessage at 0x2080e0a6e10>)

In [29]:
for index, row in imdb.iterrows():
    print(row['Rank & Title'],row['IMDb Rating'])

1. Anand (1971) 8.7
2. Drishyam (2013) 8.6
3. Nayakan (1987) 8.6
4. Anbe Sivam (2003) 8.5
5. Gol Maal (1979) 8.5
6. Vikram Vedha (2017) 8.5
7. Black Friday (2004) 8.5
8. Ratsasan (2018) 8.4
9. Dangal (2016) 8.4
10. Pather Panchali (1955) 8.4
11. Uri: The Surgical Strike (2019) 8.4
12. Taare Zameen Par (2007) 8.4
13. Andhadhun (2018) 8.4
14. 3 Idiots (2009) 8.4
15. Aruvi (2016) 8.3
16. 96 (2018) 8.3
17. Manichithrathazhu (1993) 8.3
18. Jaane Bhi Do Yaaro (1983) 8.3
19. Thalapathi (1991) 8.3
20. Guide (1965) 8.3
21. Chupke Chupke (1975) 8.3
22. Thani Oruvan (2015) 8.2
23. Kannathil Muthamittal (2002) 8.2
24. Khosla Ka Ghosla! (2006) 8.2
25. Gully Boy (2019) 8.2
26. The World of Apu (1959) 8.2
27. Vada Chennai (2018) 8.2
28. Dhuruvangal Pathinaaru (2016) 8.2
29. Peranbu (2018) 8.2
30. Shahid (2012) 8.2
31. Talvar (2015) 8.2
32. Drishyam (2015) 8.2
33. Mughal-E-Azam (1960) 8.2
34. Aparajito (1956) 8.2
35. Black (2005) 8.2
36. Hera Pheri (2000) 8.2
37. Jigarthanda (2014) 8.1
38. Mahanati (2018) 8.1
39. Satya (1998) 8.1
40. Paan Singh Tomar (2012) 8.1
41. Rang De Basanti (2006) 8.1
42. Soodhu Kavvum (2013) 8.1
43. Bhaag Milkha Bhaag (2013) 8.1
44. Jo Jeeta Wohi Sikandar (1992) 8.1
45. Swades (2004) 8.1
46. OMG: Oh My God! (2012) 8.1
47. Queen (2013) 8.1
48. Sholay (1975) 8.1
49. Gangs of Wasseypur (2012) 8.1
50. Sairat (2016) 8.1
51. Chak de! India (2007) 8.1
52. Premam (2015) 8.1
53. Bangalore Days (2014) 8.1
54. A Wednesday (2008) 8.1
55. Tumbbad (2018) 8.1
56. Munna Bhai M.B.B.S. (2003) 8.1
57. Ustad Hotel (2012) 8.1
58. Udaan (2010) 8.1
59. Andaz Apna Apna (1994) 8.1
60. Roja (1992) 8.1
61. Dil Chahta Hai (2001) 8.1
62. Sarfarosh (1999) 8.1
63. Anniyan (2005) 8.1
64. Lagaan: Once Upon a Time in India (2001) 8.1
65. Pink (2016) 8.1
66. Kahaani (2012) 8.1
67. PK (2014) 8.1
68. Iqbal (2005) 8.1
69. Zindagi Na Milegi Dobara (2011) 8.1
70. Arjun Reddy (2017) 8.1
71. Maqbool (2003) 8.1
72. Theeran Adhigaaram Ondru (2017) 8.1
73. Masaan (2015) 8.1
74. Baasha (1995) 8.1
75. The Legend of Bhagat Singh (2002) 8.0
76. Omkara (2006) 8.0
77. Barfi! (2012) 8.0
78. Lage Raho Munna Bhai (2006) 8.0
79. Bommarillu (2006) 8.0
80. Bombay (1995) 8.0
81. Deewaar (1975) 8.0
82. Lucia (2013) 8.0
83. Ugly (2013) 8.0
84. Dilwale Dulhania Le Jayenge (1995) 8.0
85. Mother India (1957) 8.0
86. Gulaal (2009) 8.0
87. Baahubali 2: The Conclusion (2017) 8.0
88. Padosan (1968) 8.0
89. Haider (2014) 8.0
90. Indian (1996) 8.0
91. Athadu (2005) 8.0
92. Dev.D (2009) 8.0
93. Vedam (2010) 8.0
94. Special 26 (2013) 8.0
95. Company (2002) 7.9
96. Vaastav: The Reality (1999) 7.9
97. Badhaai Ho (2018) 7.9
98. Bajrangi Bhaijaan (2015) 7.9
99. Ship of Theseus (2012) 7.9
100. Manjhi: The Mountain Man (2015) 7.9
101. Ankhon Dekhi (2013) 7.9
102. Pizza (2012) 7.9
103. Badla (2019) 7.9
104. Jab We Met (2007) 7.9
105. Dor (2006) 7.9
106. Padman (2018) 7.9
107. Kal Ho Naa Ho (2003) 7.9
108. Airlift (2016) 7.9
109. Hey Ram (2000) 7.9
110. Baby (2015) 7.9
111. Vaaranam Aayiram (2008) 7.9
112. My Name Is Khan (2010) 7.9
113. Rangasthalam (2018) 7.9
114. K.G.F: Chapter 1 (2018) 7.9
115. Secret Superstar (2017) 7.8
116. Lakshya (2004) 7.8
117. Baahubali: The Beginning (2015) 7.8
118. Border (1997) 7.8
119. Ab Tak Chhappan (2004) 7.8
120. Vettaiyaadu Vilaiyaadu (2006) 7.8
121. Gangaajal (2003) 7.8
122. Johnny Gaddaar (2007) 7.8
123. Manam (2014) 7.8
124. English Vinglish (2012) 7.8
125. Okkadu (2003) 7.8
126. Ulidavaru Kandanthe (2014) 7.8
127. The Lunchbox (2013) 7.8
128. Rock On!! (2008) 7.8
129. Don (1978) 7.8
130. Mr. India (1987) 7.8
131. Udta Punjab (2016) 7.7
132. Nayak: The Real Hero (2001) 7.7
133. Hindi Medium (2017) 7.7
134. Dasvidaniya (2008) 7.7
135. Vicky Donor (2012) 7.7
136. Raazi (2018) 7.7
137. Oye Lucky! Lucky Oye! (2008) 7.7
138. Mumbai Meri Jaan (2008) 7.7
139. Guru (2007) 7.7
140. Samsara (2001) 7.7
141. Pokiri (2006) 7.7
142. Veer-Zaara (2004) 7.7
143. Charlie (2015) 7.7
144. Earth (1998) 7.7
145. Aamir (2008) 7.7
146. Kapoor & Sons (2016) 7.7
147. Agneepath (1990) 7.7
148. Newton (2017) 7.7
149. RangiTaranga (2015) 7.7
150. Eega (2012) 7.7
151. Pyaar Ka Punchnama (2011) 7.7
152. Neerja (2016) 7.7
153. Manorama Six Feet Under (2007) 7.7
154. Madras Cafe (2013) 7.6
155. Sarkar (2005) 7.6
156. Sanju (2018) 7.6
157. Kabhi Haan Kabhi Naa (1994) 7.6
158. Darr (1993) 7.6
159. Stree (2018) 7.6
160. Bheja Fry (2007) 7.6
161. Goodachari (2018) 7.6
162. Tanu Weds Manu Returns (2015) 7.6
163. Rockstar (2011) 7.6
164. 24 (2016) 7.6
165. Kai po che! (2013) 7.6
166. Kuch Kuch Hota Hai (1998) 7.6
167. Highway (2014) 7.6
168. Magadheera (2009) 7.6
169. Baazigar (1993) 7.6
170. Ek Hasina Thi (2004) 7.6
171. Saala Khadoos (2016) 7.6
172. M.S. Dhoni: The Untold Story (2016) 7.6
173. Wake Up Sid (2009) 7.6
174. Jodhaa Akbar (2008) 7.6
175. Parmanu: The Story of Pokhran (2018) 7.6
176. Dil Se.. (1998) 7.6
177. Kaththi (2014) 7.5
178. Piku (2015) 7.5
179. Devdas (2002) 7.5
180. Thuppakki (2012) 7.5
181. Delhi Belly (2011) 7.5
182. Aankhen (2002) 7.5
183. Detective Byomkesh Bakshy! (2015) 7.5
184. 1 - Nenokkadine (2014) 7.5
185. Raanjhanaa (2013) 7.5
186. Qayamat Se Qayamat Tak (1988) 7.5
187. Trapped (2016) 7.5
188. Rocket Singh: Salesman of the Year (2009) 7.5
189. Khakee (2004) 7.5
190. The Ghazi Attack (2017) 7.5
191. Amar Akbar Anthony (1977) 7.5
192. Hungama (2003) 7.5
193. Rehnaa Hai Terre Dil Mein (2001) 7.5
194. Hum Dil De Chuke Sanam (1999) 7.5
195. Hum Aapke Hain Koun...! (1994) 7.5
196. Rangeela (1995) 7.5
197. Socha Na Tha (2005) 7.5
198. Jaane Tu... Ya Jaane Na (2008) 7.5
199. Ghilli (2004) 7.5
200. Madaari (2016) 7.5
201. Ghajini (2005) 7.5
202. Dum Laga Ke Haisha (2015) 7.5
203. October (2018) 7.5
204. Jolly LLB (2013) 7.4
205. Chillar Party (2011) 7.4
206. Shaadi Mein Zaroor Aana (2017) 7.4
207. Geetha Govindam (2018) 7.4
208. Bareilly Ki Barfi (2017) 7.4
209. Sivaji (2007) 7.4
210. Peepli (Live) (2010) 7.4
211. Baghban (2003) 7.4
212. Badlapur (2015) 7.4
213. Kabhi Khushi Kabhie Gham... (2001) 7.4
214. Hichki (2018) 7.4
215. Karwaan (2018) 7.4
216. Chachi 420 (1997) 7.4
217. Guzaarish (2010) 7.4
218. Dear Zindagi (2016) 7.4
219. Mankatha (2011) 7.4
220. Once Upon a Time in Mumbaai (2010) 7.4
221. Yuva (2004) 7.4
222. Petta (2019) 7.4
223. Golmaal: Fun Unlimited (2006) 7.4
224. Kaminey (2009) 7.4
225. Life in a Metro (2007) 7.4
226. Monsoon Wedding (2001) 7.4
227. Khiladi (1992) 7.3
228. Raid (2018) 7.3
229. Page 3 (2005) 7.3
230. Ghulam (1998) 7.3
231. Khaleja (2010) 7.3
232. Maine Pyar Kiya (1989) 7.3
233. Ishqiya (2010) 7.3
234. Raman Raghav 2.0 (2016) 7.3
235. Ghajini (2008) 7.3
236. Bharat Ane Nenu (2018) 7.3
237. Lootera (2013) 7.3
238. Srimanthudu (2015) 7.3
239. Bhool Bhulaiyaa (2007) 7.3
240. Holiday (2014) 7.3
241. Parineeta (2005) 7.3
242. Ayan (2009) 7.3
243. Gold (2018) 7.3
244. Mardaani (2014) 7.3
245. Saajan (1991) 7.3
246. Taxi No. 9 2 11: Nau Do Gyarah (2006) 7.3
247. Shaitan (2011) 7.2
248. Mom (2017) 7.2
249. Te3n (2016) 7.2
250. No One Killed Jessica (2011) 7.2

In [30]:
folder_name = 'movies_images_imdb'                                      
if not folder_name in glob.glob('*'):
    os.makedirs(folder_name)

for index, row in imdb.iterrows():
    img_url = row['Poster']
    movie_name = row['Rank & Title']  
    img_extn = img_url[img_url.rfind('.'):] 
    img_name = folder_name+ '/' + movie_name + img_extn
    urllib.request.urlretrieve(img_url, img_name)

In [31]:
imdb.to_csv('imdb_top250_indian_movies_again.csv', index=False)