In [1]:
from selenium import webdriver

In [2]:
browser=webdriver.Chrome('chromedriver.exe')

In [3]:
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt

In [10]:
import os
os.getcwd()

'D:\\DBMS'

In [109]:
browser=webdriver.Chrome('chromedriver.exe')
url='https://www.naukri.com/datascience-jobs'
browser.get(url)

In [110]:
import pandas as pd
nk=pd.DataFrame()
parents=browser.find_elements_by_css_selector('div.row[type="tuple"]') #tags where <div class='row' type='tuple>'
len(parents)
for job in parents:
    job_id=job.get_attribute('id')
    #print(job_id)
    title=job.find_element_by_css_selector('li.desig').get_attribute('title')
    #print(title)
    company=job.find_element_by_css_selector('span.org').text
    #print(company)
    exp=job.find_element_by_css_selector('span.exp').text
    #print(exp)
    loc=job.find_element_by_css_selector('span.loc').text
    #print(loc)
    key_skills=job.find_element_by_css_selector('span.skill').text
    #print(key_skills)
    sal=job.find_element_by_css_selector('span.salary').text
    #print(sal)
    date=job.find_element_by_css_selector('span.date').text
    #print(date)
    url=job.get_attribute('data-url')
    #print(url)
    curr_row={'Url':url,'Job_ID':job_id,'Title':title,'Company':company,'Experience':exp,'Location':loc,'Key':key_skills,
              'Salary':sal,'Date':date}
    nk=nk.append(curr_row,ignore_index=True)
nk.to_csv('Jobs.csv')

In [59]:
def get_attribute(parent,selector,attribute):
    try:
        if attribute=='text':
            return parent.find_element_by_css_selector(selector).text
        else:
            return parent.find_element_by_css_selector(selector).get_attribute(attribute)
    except:
        val=None
    return val
parents=browser.find_elements_by_css_selector('div.row[type="tuple"]')
for job in parents:
    job_id=job.get_attribute('id')
    url=job.get_attribute('data-url')
    title=get_attribute(job,'li.desig','title')
    company=get_attribute(job,'li.desig','title')
    exp=get_attribute(job,'span.exp','text')
    loc=get_attribute(job,'span.loc','text')
    key_skills=get_attribute(job,'span.skill','text')
    sal=get_attribute(job,'span.salary','text')
    date=get_attribute(job,'span.date','text')
    curr_row={'Url':url,'Job_ID':job_id,'Title':title,'Company':company,'Experience':exp,'Location':loc,'Key':key_skills,
              'Salary':sal,'Date':date}
    nk=nk.append(curr_row,ignore_index=True)
nk

,Company,Date,Experience,Job_ID,Key,Location,Salary,Title,Url
0,WebTek Labs Pvt. Ltd.,1 day ago,2-5 yrs,050319005958,"presentable, data science, communication skill...",Delhi NCR(Rajouri garden),"2,00,000 - 3,50,000 P.A.",Data Science Trainer,https://www.naukri.com/job-listings-Data-Scien...
1,"Optum, a UnitedHealth Group Company",1 day ago,8-13 yrs,050319900979,"Senior Manager - Data Science - Gurgaon, HR",Gurgaon,Not disclosed,"Senior Manager - Data Science - Gurgaon, HR",https://www.naukri.com/job-listings-Senior-Man...
2,Senseforth Technologies - Startup,1 day ago,1-6 yrs,050319900184,"HTML, Core Java, CSS, Advanced Java, MySQL, PH...",Bengaluru,Not disclosed,Senior Software Engineer,https://www.naukri.com/job-listings-Senior-Sof...
3,Indegene,1 day ago,8-13 yrs,050319901870,"Deep Learning, Java, Python, Data Science, Mac...",Bengaluru,Not disclosed,Engineering Lead,https://www.naukri.com/job-listings-Engineerin...
4,R2R CONSULTANTS LLP,2 days ago,1-6 yrs,040319005279,"Data Science, Data Analytics, Data Scientist, ...",Mumbai,"7,50,000 - 16,00,000 P.A.",Excellent Opening for Financial Analytics Spec...,https://www.naukri.com/job-listings-Excellent-...
5,GAMAKA Artificial Intelligence Solutions,1 day ago,0-0 yrs,050319000669,"python, panda, machine learning, data science, R",Pune,Not disclosed,"Python Intern, R Intern, Internship Trainee,",https://www.naukri.com/job-listings-Python-Int...
6,Simplynaukri,1 day ago,4-7 yrs,050319901251,"Data Science, Predictive Analytics, Neural Net...",Bengaluru,Not disclosed,Data Scientist/ Statistical Modeler - Machine ...,https://www.naukri.com/job-listings-Data-Scien...
7,Wipro GSH (A Division of Wipro Limited),1 day ago,12-12 yrs,050319900836,"Renewable energy, Agile, Machine learning, Com...",Bengaluru,Not disclosed,Advanced Analytics - Solution Lead,https://www.naukri.com/job-listings-Advanced-A...
8,R2R CONSULTANTS LLP,2 days ago,3-8 yrs,040319005497,"Data Science, Data Analytics, Data Scientist, ...",Mumbai,"10,00,000 - 16,00,000 P.A.",Opening for Supply Chain Analytics Specialist ...,https://www.naukri.com/job-listings-Opening-fo...
9,Squareroot,1 day ago,8-12 yrs,040319900698,"Data Science, Machine Learning, Analytics, Fin...",Bengaluru,Not disclosed,Head - Data Scientist - Startup,https://www.naukri.com/job-listings-Head-Data-...
10,Wipro Ltd,2 days ago,5-10 yrs,040319900006,Data Science,"Hyderabad, Hyderabad",Not disclosed,Consultant Analytics,https://www.naukri.com/job-listings-Consultant...
11,Squareroot Consulting Pvt Ltd,1 day ago,1-5 yrs,050319902498,"Javascript, HTML, UI Development, React.Js, So...",Bengaluru,Not disclosed,Software Engineer - UI Development - React.js/...,https://www.naukri.com/job-listings-Software-E...
12,HuQuo Consulting Pvt. Ltd.,1 day ago,2-5 yrs,050319005681,"Analyst - Data Science, Python, SQL, R, machin...",Gurgaon,Not disclosed,Senior Analyst - Data Science - Iit/nit/iim/xl...,https://www.naukri.com/job-listings-Senior-Ana...
13,HuQuo Consulting Pvt. Ltd.,1 day ago,5-10 yrs,050319005573,"Analytics, Python, data science, ETL, Deep Mac...",Gurgaon,Not disclosed,Manager - Analytics - Deep Machine Learning - ...,https://www.naukri.com/job-listings-Manager-An...
14,Staffio HR,1 day ago,1-5 yrs,050319004041,"Data Scientist, Machine Learning, R, Python, d...",Pune,Not disclosed,Data Scientist - Machine Learning/r/python,https://www.naukri.com/job-listings-Data-Scien...
15,Piford Technologies Private Limited.,1 day ago,0-5 yrs,050319005962,"web development, php, java, software testing, ...","Chandigarh, Mohali","1,25,000 - 3,00,000 P.A. Best Stipend as per I...",Fresher Software Trainee / Internship in Pifo...,https://www.naukri.com/job-listings-Fresher-So...
16,ASM Technologies Ltd,1 day ago,4-6 yrs,050319005740,"sql, data science, tableau, data visualization...",Bengaluru,Not disclosed,Job Opening for Business Analytics (hive/ Bi...,https://www.naukri.com/job-listings-Opening-fo...
17,Startup - Shipsy,1 day ago,1-3 yrs,040319000414,"Java, Software Development Life Cycle, SQL, Ja...",Gurgaon,Not disclosed,Senior Software Engineer,https://www.naukri.com/job-listings-Senior-Sof...
18,UNCAP RESEARCH LABS PVT LTD,1 day ago,1-5 yrs,050319007041,"Recruitment, Talent Acquisition, Sourcing, Lin...",Gurgaon,"5,00,000 - 8,00,000 P.A.",Talent Evangelist,https://www.naukri.com/job-listings-Talent-Eva...
19,Ecozen- Startup,1 day ago,2-4 yrs,050319900056,"Data Scientist, Data Science, Python, R, Predi...",Pune,Not disclosed,Data Scientist,https://www.naukri.com/job-listings-Data-Scien...
20,Real Time Signals Technologies,2 days ago,0-3 yrs,040319000022,"java, javascript, mysql, core java, web techno...",Bengaluru,"50,000 - 1,00,000 P.A.",Intern Software Engineer,https://www.naukri.com/job-listings-Intern-Sof...
21,vConstruct Private Limited,1 day ago,8-13 yrs,050319008025,"Data Mining, Data Analysis, Data Science, Pric...",Pune(Hadapsar),Not disclosed,Data Science Business Manager,https://www.naukri.com/job-listings-Data-Scien...
22,Rinalytics Advisors,1 day ago,10-15 yrs,050319901247,"Machine Learning, Text Mining, Data Mining, Da...",Bengaluru,Not disclosed,VP - Machine Learning/ Advanced Analytics - KPO,https://www.naukri.com/job-listings-VP-Machine...
23,Tally Solutions Pvt. Ltd,2 days ago,12-16 yrs,040319901592,"Product Strategy, Product Management, Business...",Bengaluru,Not disclosed,Associate Director - Product Management,https://www.naukri.com/job-listings-Associate-...
24,Shell India Markets Private Limited,2 days ago,2-3 yrs,040319900570,"Factor Analysis, Deep Learning, Neural Network...",Chennai,Not disclosed,Team Lead - Data Science,https://www.naukri.com/job-listings-Team-Lead-...
25,Cashify,1 day ago,3-7 yrs,040319003318,"Text Mining, Data Mining, Predictive Modeling,...",Gurgaon,"12,00,000 - 20,00,000 P.A.",Data Scientist / Decision Analyst,https://www.naukri.com/job-listings-Data-Scien...
26,Maveric Systems Limited,2 days ago,3-8 yrs,040319007118,"machine learning, neural networks, artificial ...",Chennai,Not disclosed,Maveric Systems Ltd - Hiring ML Engineer - Che...,https://www.naukri.com/job-listings-Maveric-Sy...
27,Senseforth Technologies - Startup,1 day ago,1-4 yrs,050319900190,"Core Java, J2Ee, Spark, MySQL, Hadoop, Python,...",Bengaluru,Not disclosed,Senior Software Engineer-ii,https://www.naukri.com/job-listings-Senior-Sof...
28,Live Connections,1 day ago,8-11 yrs,050319004125,"Data Science, SAS SQL, Techno Functional, Conn...",Bengaluru,Not disclosed,Business Analyst - Data Management - Investmen...,https://www.naukri.com/job-listings-Business-A...
29,MASTERCARD TECHNOLOGIES PRIVATE LIMITED,1 day ago,5-10 yrs,070219007736,"nlp, r, data science, machine learning, python...",Gurgaon,Not disclosed,"Mastercard :: AI Manager, Product Development ...",https://www.naukri.com/job-listings-Mastercard...
...,...,...,...,...,...,...,...,...,...
70,Intern Software Engineer,2 days ago,0-3 yrs,040319000022,"java, javascript, mysql, core java, web techno...",Bengaluru,"50,000 - 1,00,000 P.A.",Intern Software Engineer,https://www.naukri.com/job-listings-Intern-Sof...
71,Data Science Business Manager,1 day ago,8-13 yrs,050319008025,"Data Mining, Data Analysis, Data Science, Pric...",Pune(Hadapsar),Not disclosed,Data Science Business Manager,https://www.naukri.com/job-listings-Data-Scien...
72,VP - Machine Learning/ Advanced Analytics - KPO,1 day ago,10-15 yrs,050319901247,"Machine Learning, Text Mining, Data Mining, Da...",Bengaluru,Not disclosed,VP - Machine Learning/ Advanced Analytics - KPO,https://www.naukri.com/job-listings-VP-Machine...
73,Associate Director - Product Management,2 days ago,12-16 yrs,040319901592,"Product Strategy, Product Management, Business...",Bengaluru,Not disclosed,Associate Director - Product Management,https://www.naukri.com/job-listings-Associate-...
74,Team Lead - Data Science,2 days ago,2-3 yrs,040319900570,"Factor Analysis, Deep Learning, Neural Network...",Chennai,Not disclosed,Team Lead - Data Science,https://www.naukri.com/job-listings-Team-Lead-...
75,Data Scientist / Decision Analyst,1 day ago,3-7 yrs,040319003318,"Text Mining, Data Mining, Predictive Modeling,...",Gurgaon,"12,00,000 - 20,00,000 P.A.",Data Scientist / Decision Analyst,https://www.naukri.com/job-listings-Data-Scien...
76,Maveric Systems Ltd - Hiring ML Engineer - Che...,2 days ago,3-8 yrs,040319007118,"machine learning, neural networks, artificial ...",Chennai,Not disclosed,Maveric Systems Ltd - Hiring ML Engineer - Che...,https://www.naukri.com/job-listings-Maveric-Sy...
77,Senior Software Engineer-ii,1 day ago,1-4 yrs,050319900190,"Core Java, J2Ee, Spark, MySQL, Hadoop, Python,...",Bengaluru,Not disclosed,Senior Software Engineer-ii,https://www.naukri.com/job-listings-Senior-Sof...
78,Business Analyst - Data Management - Investmen...,1 day ago,8-11 yrs,050319004125,"Data Science, SAS SQL, Techno Functional, Conn...",Bengaluru,Not disclosed,Business Analyst - Data Management - Investmen...,https://www.naukri.com/job-listings-Business-A...
79,"Mastercard :: AI Manager, Product Development ...",1 day ago,5-10 yrs,070219007736,"nlp, r, data science, machine learning, python...",Gurgaon,Not disclosed,"Mastercard :: AI Manager, Product Development ...",https://www.naukri.com/job-listings-Mastercard...
80,Tech Lead | Fast Growing Comm-tech Startup | G...,1 day ago,1-2 yrs,050319007328,"Big Data, Data Science, Tech Lead, Team Handli...","Delhi, Gurgaon",Not disclosed,Tech Lead | Fast Growing Comm-tech Startup | G...,https://www.naukri.com/job-listings-Tech-Lead-...
81,Data Science (jupyter/azure Ml/matlab),1 day ago,1-5 yrs,010319901757,"Python, Data modeling, MATLAB, SPSS, Computer ...",Bengaluru,Not disclosed,Data Science (jupyter/azure Ml/matlab),https://www.naukri.com/job-listings-Data-Scien...
82,Excellent Opening for Sales Analytics Speciali...,2 days ago,1-6 yrs,040319005356,"Data Science, Data Analytics, Data Scientist, ...",Mumbai,"7,50,000 - 16,00,000 P.A.",Excellent Opening for Sales Analytics Speciali...,https://www.naukri.com/job-listings-Excellent-...
83,Data Scientist - Nlp/r/python,1 day ago,2-5 yrs,040319001334,"python, nlp, data science, r, data analytics, ...",Hyderabad,Not disclosed,Data Scientist - Nlp/r/python,https://www.naukri.com/job-listings-Data-Scien...
84,Big Data Solution Architect - R/python,1 day ago,12-15 yrs,040319900845,"Java, Hadoop, NoSQL, SQL Server, Cassandra, R,...",Navi Mumbai,Not disclosed,Big Data Solution Architect - R/python,https://www.naukri.com/job-listings-Big-Data-S...
85,Data Scientist - Austrian MNC - Gurgaon,1 day ago,1-6 yrs,050319007259,"c, machine learning, c++, python, java, data s...",Gurgaon(Udyog Vihar),"10,00,000 - 20,00,000 P.A.",Data Scientist - Austrian MNC - Gurgaon,https://www.naukri.com/job-listings-Data-Scien...
86,Software Lead,1 day ago,2-4 yrs,050319900082,"Software Lead, software development, Embedded,...",Pune,Not disclosed,Software Lead,https://www.naukri.com/job-listings-Software-L...
87,Product Manager,1 day ago,5-8 yrs,050319001376,"Sales Engineering, Marketing, Product Design, ...",Mumbai,Not disclosed,Product Manager,https://www.naukri.com/job-listings-Product-Ma...
88,Job Openings for Software Developer,1 day ago,0-1 yrs,230219005383,"Python, Artificial Intelligence, Machine Learn...",Bengaluru(Mahadeva Kodigehalli),"2,50,000 - 3,50,000 P.A.",Job Openings for Software Developer,https://www.naukri.com/job-listings-Openings-f...
89,Job Openings for Software Developer,1 day ago,0-1 yrs,230219005388,"Python, Artificial Intelligence, Machine Learn...",Bengaluru(Electronics City Phase 1),"2,50,000 - 3,50,000 P.A.",Job Openings for Software Developer,https://www.naukri.com/job-listings-Openings-f...
90,Job Openings for Software Developer,1 day ago,0-1 yrs,230219005004,"Python, Artificial Intelligence, Machine Learn...",Bengaluru(Rajaji Nagar),"2,50,000 - 3,50,000 P.A.",Job Openings for Software Developer,https://www.naukri.com/job-listings-Openings-f...
91,Backed Programmer - IoT - Iit/bits,1 day ago,2-5 yrs,280219000716,"Python, Javascript, Pyramid, Software Developm...",Bengaluru,Not disclosed,Backed Programmer - IoT - Iit/bits,https://www.naukri.com/job-listings-Backed-Pro...
92,Senior Data Associate,1 day ago,1-5 yrs,010319900071,"Text Mining, Hive, NoSQL, Data Science, Python...",Mumbai,Not disclosed,Senior Data Associate,https://www.naukri.com/job-listings-Senior-Dat...
93,Engineering Director - Machine Learning/ AI - ...,1 day ago,15-20 yrs,270219002215,"Python, Deep Learning, Django, NLP, Data Scien...",Bengaluru,Not disclosed,Engineering Director - Machine Learning/ AI - ...,https://www.naukri.com/job-listings-Engineerin...
94,Quantitative Analyst - Validation Specialist,1 day ago,3-7 yrs,280219006604,"data science, java, machine learning, python, ...",Mumbai,"20,00,000 - 27,50,000 P.A.",Quantitative Analyst - Validation Specialist,https://www.naukri.com/job-listings-Quantitati...
95,Engineering Director - Machine Learning/ AI - ...,1 day ago,10-15 yrs,270219002207,"Python, Deep Learning, Django, NLP, Data Scien...",Bengaluru,Not disclosed,Engineering Director - Machine Learning/ AI - ...,https://www.naukri.com/job-listings-Engineerin...
96,SAS Fraud Analyst,1 day ago,5-7 yrs,010319001172,"Base SAS, Statistical Modeling, Data Science, ...",Delhi,Not disclosed,SAS Fraud Analyst,https://www.naukri.com/job-listings-SAS-Fraud-...
97,Data Scientist,1 day ago,6-10 yrs,280219003575,"Deep Learning, Hadoop, Hive, Text Mining, NLP,...",Bengaluru,Not disclosed,Data Scientist,https://www.naukri.com/job-listings-Data-Scien...
98,Senior Consultant (machine Learning & Data Sci...,1 day ago,10-20 yrs,250219002257,"Data Science, Machine Learning, Project Planni...",Bengaluru,Not disclosed,Senior Consultant (machine Learning & Data Sci...,https://www.naukri.com/job-listings-Senior-Con...
99,"Data Scientist, TVS Next",1 day ago,9-14 yrs,280219007838,"Data Science, Machine Learning, R, Python, SQL...",Bengaluru,Not disclosed,"Data Scientist, TVS Next",https://www.naukri.com/job-listings-Data-Scien...

# Scrapping through multiple pages

In [ ]:
url='https://www.naukri.com/datascience-jobs'
url='https://www.naukri.com/datascience-jobs-2'
url='https://www.naukri.com/datascience-jobs-3'

In [66]:
import time
jobs_df=pd.DataFrame()
def get_attribute(parent,selector,attribute):
    try:
        if attribute=='text':
            return parent.find_element_by_css_selector(selector).text
        else:
            return parent.find_element_by_css_selector(selector).get_attribute(attribute)
    except:
        val=None
    return val
for i in range(1,10):
    url='https://www.naukri.com/datascience-jobs-%d' % i
    browser.get(url)
    time.sleep(2)
    print(i)
    parents=browser.find_elements_by_css_selector('div.row[type="tuple"]')
    for job in parents:
        job_id=job.get_attribute('id')
        url=job.get_attribute('data-url')
        title=get_attribute(job,'li.desig','title')
        company=get_attribute(job,'li.desig','title')
        exp=get_attribute(job,'span.exp','text')
        loc=get_attribute(job,'span.loc','text')
        key_skills=get_attribute(job,'span.skill','text')
        sal=get_attribute(job,'span.salary','text')
        date=get_attribute(job,'span.date','text')
        curr_row={'Url':url,'Job_ID':job_id,'Title':title,'Company':company,'Experience':exp,'Location':loc,'Key':key_skills,
                  'Salary':sal,'Date':date}
        jobs_df=jobs_df.append(curr_row,ignore_index=True)
jobs_df

1
2
3
4
5
6
7
8
9

,Company,Date,Experience,Job_ID,Key,Location,Salary,Title,Url
0,Excellent Opening for Financial Analytics Spec...,2 days ago,1-6 yrs,040319005279,"Data Science, Data Analytics, Data Scientist, ...",Mumbai,"7,50,000 - 16,00,000 P.A.",Excellent Opening for Financial Analytics Spec...,https://www.naukri.com/job-listings-Excellent-...
1,Opening for Supply Chain Analytics Specialist ...,2 days ago,3-8 yrs,040319005497,"Data Science, Data Analytics, Data Scientist, ...",Mumbai,"10,00,000 - 16,00,000 P.A.",Opening for Supply Chain Analytics Specialist ...,https://www.naukri.com/job-listings-Opening-fo...
2,Senior Consultant/consultant/assistant Manager...,Just Now,2-5 yrs,060319000799,"data science, neural networks, r, machine lear...",Bengaluru,Not disclosed,Senior Consultant/consultant/assistant Manager...,https://www.naukri.com/job-listings-Senior-Con...
3,Engineering Lead,1 day ago,8-13 yrs,050319901870,"Deep Learning, Java, Python, Data Science, Mac...",Bengaluru,Not disclosed,Engineering Lead,https://www.naukri.com/job-listings-Engineerin...
4,Data Science Business Manager,1 day ago,8-13 yrs,050319008025,"Data Mining, Data Analysis, Data Science, Pric...",Pune(Hadapsar),Not disclosed,Data Science Business Manager,https://www.naukri.com/job-listings-Data-Scien...
5,Data Scientist - Austrian MNC - Gurgaon,1 day ago,1-6 yrs,050319007259,"c, machine learning, c++, python, java, data s...",Gurgaon(Udyog Vihar),"10,00,000 - 20,00,000 P.A.",Data Scientist - Austrian MNC - Gurgaon,https://www.naukri.com/job-listings-Data-Scien...
6,Fresher Software Trainee / Internship in Pifo...,1 day ago,0-5 yrs,050319005962,"web development, php, java, software testing, ...","Chandigarh, Mohali","1,25,000 - 3,00,000 P.A. Best Stipend as per I...",Fresher Software Trainee / Internship in Pifo...,https://www.naukri.com/job-listings-Fresher-So...
7,Data Scientist/ Statistical Modeler - Machine ...,1 day ago,4-7 yrs,050319901251,"Data Science, Predictive Analytics, Neural Net...",Bengaluru,Not disclosed,Data Scientist/ Statistical Modeler - Machine ...,https://www.naukri.com/job-listings-Data-Scien...
8,Senior Software Engineer,1 day ago,1-6 yrs,050319900184,"HTML, Core Java, CSS, Advanced Java, MySQL, PH...",Bengaluru,Not disclosed,Senior Software Engineer,https://www.naukri.com/job-listings-Senior-Sof...
9,Advanced Analytics - Solution Lead,1 day ago,12-12 yrs,050319900836,"Renewable energy, Agile, Machine learning, Com...",Bengaluru,Not disclosed,Advanced Analytics - Solution Lead,https://www.naukri.com/job-listings-Advanced-A...
10,Head - Data Scientist - Startup,1 day ago,8-12 yrs,040319900698,"Data Science, Machine Learning, Analytics, Fin...",Bengaluru,Not disclosed,Head - Data Scientist - Startup,https://www.naukri.com/job-listings-Head-Data-...
11,Team Lead - Data Science,2 days ago,2-3 yrs,040319900570,"Factor Analysis, Deep Learning, Neural Network...",Chennai,Not disclosed,Team Lead - Data Science,https://www.naukri.com/job-listings-Team-Lead-...
12,Data Science Trainer,1 day ago,2-5 yrs,050319005958,"presentable, data science, communication skill...",Delhi NCR(Rajouri garden),"2,00,000 - 3,50,000 P.A.",Data Science Trainer,https://www.naukri.com/job-listings-Data-Scien...
13,Senior Analyst - Data Science - Iit/nit/iim/xl...,1 day ago,2-5 yrs,050319005681,"Analyst - Data Science, Python, SQL, R, machin...",Gurgaon,Not disclosed,Senior Analyst - Data Science - Iit/nit/iim/xl...,https://www.naukri.com/job-listings-Senior-Ana...
14,Manager - Analytics - Deep Machine Learning - ...,1 day ago,5-10 yrs,050319005573,"Analytics, Python, data science, ETL, Deep Mac...",Gurgaon,Not disclosed,Manager - Analytics - Deep Machine Learning - ...,https://www.naukri.com/job-listings-Manager-An...
15,Data Scientist - Machine Learning/r/python,1 day ago,1-5 yrs,050319004041,"Data Scientist, Machine Learning, R, Python, d...",Pune,Not disclosed,Data Scientist - Machine Learning/r/python,https://www.naukri.com/job-listings-Data-Scien...
16,Data Scientist,1 day ago,2-4 yrs,050319900056,"Data Scientist, Data Science, Python, R, Predi...",Pune,Not disclosed,Data Scientist,https://www.naukri.com/job-listings-Data-Scien...
17,Software Lead,1 day ago,2-4 yrs,050319900082,"Software Lead, software development, Embedded,...",Pune,Not disclosed,Software Lead,https://www.naukri.com/job-listings-Software-L...
18,Data Scientist - Nlp/r/python,1 day ago,2-5 yrs,040319001334,"python, nlp, data science, r, data analytics, ...",Hyderabad,Not disclosed,Data Scientist - Nlp/r/python,https://www.naukri.com/job-listings-Data-Scien...
19,Consultant Analytics,2 days ago,5-10 yrs,040319900006,Data Science,"Hyderabad, Hyderabad",Not disclosed,Consultant Analytics,https://www.naukri.com/job-listings-Consultant...
20,Senior Software Engineer-ii,1 day ago,1-4 yrs,050319900190,"Core Java, J2Ee, Spark, MySQL, Hadoop, Python,...",Bengaluru,Not disclosed,Senior Software Engineer-ii,https://www.naukri.com/job-listings-Senior-Sof...
21,Maveric Systems Ltd - Hiring ML Engineer - Che...,2 days ago,3-8 yrs,040319007118,"machine learning, neural networks, artificial ...",Chennai,Not disclosed,Maveric Systems Ltd - Hiring ML Engineer - Che...,https://www.naukri.com/job-listings-Maveric-Sy...
22,Excellent Opening for Sales Analytics Speciali...,2 days ago,1-6 yrs,040319005356,"Data Science, Data Analytics, Data Scientist, ...",Mumbai,"7,50,000 - 16,00,000 P.A.",Excellent Opening for Sales Analytics Speciali...,https://www.naukri.com/job-listings-Excellent-...
23,VP - Machine Learning/ Advanced Analytics - KPO,1 day ago,10-15 yrs,050319901247,"Machine Learning, Text Mining, Data Mining, Da...",Bengaluru,Not disclosed,VP - Machine Learning/ Advanced Analytics - KPO,https://www.naukri.com/job-listings-VP-Machine...
24,Delivery Head for Delhi/ncr,Just Now,15-20 yrs,060319000776,"data integration, data modeling, data governan...",Delhi NCR,Not disclosed,Delivery Head for Delhi/ncr,https://www.naukri.com/job-listings-Delivery-H...
25,Senior Software Engineer,1 day ago,1-3 yrs,040319000414,"Java, Software Development Life Cycle, SQL, Ja...",Gurgaon,Not disclosed,Senior Software Engineer,https://www.naukri.com/job-listings-Senior-Sof...
26,Data Scientist / Decision Analyst,1 day ago,3-7 yrs,040319003318,"Text Mining, Data Mining, Predictive Modeling,...",Gurgaon,"12,00,000 - 20,00,000 P.A.",Data Scientist / Decision Analyst,https://www.naukri.com/job-listings-Data-Scien...
27,"Python Intern, R Intern, Internship Trainee,",1 day ago,0-0 yrs,050319000669,"python, panda, machine learning, data science, R",Pune,Not disclosed,"Python Intern, R Intern, Internship Trainee,",https://www.naukri.com/job-listings-Python-Int...
28,"Senior Manager - Data Science - Gurgaon, HR",1 day ago,8-13 yrs,050319900979,"Senior Manager - Data Science - Gurgaon, HR",Gurgaon,Not disclosed,"Senior Manager - Data Science - Gurgaon, HR",https://www.naukri.com/job-listings-Senior-Man...
29,Intern Software Engineer,2 days ago,0-3 yrs,040319000022,"java, javascript, mysql, core java, web techno...",Bengaluru,"50,000 - 1,00,000 P.A.",Intern Software Engineer,https://www.naukri.com/job-listings-Intern-Sof...
...,...,...,...,...,...,...,...,...,...
420,Head - Data Science/machine Learning - Telecom...,30+ days ago,15-25 yrs,021118901097,"Data Science, Machine Learning, Analytics, Big...",Bengaluru,Not disclosed,Head - Data Science/machine Learning - Telecom...,https://www.naukri.com/job-listings-Head-Data-...
421,Senior lead Artificial Intelligence role,30+ days ago,12-14 yrs,310119900282,"deep learning, c, machine learning, nlp, pytho...",Mumbai,Not disclosed,Senior lead Artificial Intelligence role,https://www.naukri.com/job-listings-Senior-lea...
422,Senior Artificial Intelligence role,30+ days ago,10-12 yrs,310119900279,"Deep Learning, C, Machine Learning, NLP, Pytho...",Mumbai,Not disclosed,Senior Artificial Intelligence role,https://www.naukri.com/job-listings-Senior-Art...
423,Data Scientist,30+ days ago,2-6 yrs,310119004536,"machine learning, analytics, statistical model...",Bengaluru,Not disclosed,Data Scientist,https://www.naukri.com/job-listings-Data-Scien...
424,Data Scientist - Machine Learning/ Artificial ...,30+ days ago,4-8 yrs,310119001807,"Data Science, Machine Learning, Artificial Int...",Mumbai,Not disclosed,Data Scientist - Machine Learning/ Artificial ...,https://www.naukri.com/job-listings-Data-Scien...
425,Data Scientist - ETL/ Analytics,30+ days ago,3-6 yrs,300818900889,"Data Science, Machine Learning, SQL, Python, R...",Mumbai,Not disclosed,Data Scientist - ETL/ Analytics,https://www.naukri.com/job-listings-Data-Scien...
426,Data Scientist - Machine Learning - Edutech - ...,30+ days ago,0-4 yrs,300119901520,"Machine Learning, Python, Statistics, Analytic...",Bengaluru,Not disclosed,Data Scientist - Machine Learning - Edutech - ...,https://www.naukri.com/job-listings-Data-Scien...
427,Sr. Engineer - Machine Learning (retail Domain),30+ days ago,4-8 yrs,300119901225,"deep learning, machine learning, power user, a...",Bengaluru,Not disclosed,Sr. Engineer - Machine Learning (retail Domain),https://www.naukri.com/job-listings-Sr-Enginee...
428,Machine Learning and Data Scientist,30+ days ago,5-7 yrs,300119901224,"deep learning, neural networks, predictive mod...",Bengaluru,Not disclosed,Machine Learning and Data Scientist,https://www.naukri.com/job-listings-Machine-Le...
429,Senior Data Scientist - Retail,30+ days ago,8-13 yrs,300119900355,"Retail, R, Python, SAS, Problem Solving, data ...",Bengaluru,Not disclosed,Senior Data Scientist - Retail,https://www.naukri.com/job-listings-Senior-Dat...
430,Data Scientist (senior Manager) - Mumbai,30+ days ago,10-12 yrs,300119005132,"Natural Language Processing, C, Java, Python, ...",Mumbai,Not disclosed,Data Scientist (senior Manager) - Mumbai,https://www.naukri.com/job-listings-Data-Scien...
431,Data Scientist (assistant Manager) - Mumbai,30+ days ago,5-7 yrs,300119005086,"Natural Language Processing, C, Java, Python, ...",Mumbai,Not disclosed,Data Scientist (assistant Manager) - Mumbai,https://www.naukri.com/job-listings-Data-Scien...
432,Qlikview Architect,30+ days ago,8-12 yrs,290119005736,"Data Science, Data Warehousing, Business Intel...",Bengaluru(Indira Nagar),"9,00,000 - 18,00,000 P.A.",Qlikview Architect,https://www.naukri.com/job-listings-Qlikview-A...
433,Qlikview Architect,30+ days ago,8-12 yrs,290119005718,"Data Science, Data Warehousing, Business Intel...",Bengaluru(Indira Nagar),"9,00,000 - 18,00,000 P.A.",Qlikview Architect,https://www.naukri.com/job-listings-Qlikview-A...
434,Manager - Data Scientist - Media - IIT,30+ days ago,5-8 yrs,280119003850,"Logistic Regression, Arima, SAS, R, Time Serie...",Mumbai,Not disclosed,Manager - Data Scientist - Media - IIT,https://www.naukri.com/job-listings-Manager-Da...
435,Manager/senior Manager - Analytics/python - CP...,30+ days ago,7-10 yrs,280119001282,"machine learning, data science, neural network...",Bengaluru,Not disclosed,Manager/senior Manager - Analytics/python - CP...,https://www.naukri.com/job-listings-Manager-se...
436,Manager/senior Manager - Analytics/python - CPG,30+ days ago,7-10 yrs,280119001252,"Machine Learning, Data Science, Neural Network...",Bengaluru,Not disclosed,Manager/senior Manager - Analytics/python - CPG,https://www.naukri.com/job-listings-Manager-se...
437,Data Scientist - Etl/analytics,30+ days ago,3-6 yrs,250119008617,"Data Science, Machine Learning, SQL, Python, R...",Mumbai,Not disclosed,Data Scientist - Etl/analytics,https://www.naukri.com/job-listings-Data-Scien...
438,Data Scientist - Machine Learning/artificial I...,30+ days ago,4-8 yrs,250119008279,"Data Science, Machine Learning, Artificial Int...",Mumbai,Not disclosed,Data Scientist - Machine Learning/artificial I...,https://www.naukri.com/job-listings-Data-Scien...
439,Data Scientist,30+ days ago,2-4 yrs,250119000376,"Data Science, NoSQL, Information Retrieval, Ma...",India,Not disclosed,Data Scientist,https://www.naukri.com/job-listings-Data-Scien...
440,Lead System Administrator - Network Senior Man...,30+ days ago,8-12 yrs,230119901103,"Hive, Data Science, R, Python, Machine Learnin...","Delhi NCR, Gurgaon",Not disclosed,Lead System Administrator - Network Senior Man...,https://www.naukri.com/job-listings-Lead-Syste...
441,Head- Corporate Python Trainer,30+ days ago,10-20 yrs,230119900035,"Python, Django, Data Science, Bootstrap, Torna...",Hyderabad,Not disclosed,Head- Corporate Python Trainer,https://www.naukri.com/job-listings-Head-Corpo...
442,Head-corporate Python Trainer,30+ days ago,3-8 yrs,230119900032,"Python, Django, Data Science, Bootstrap, Torna...",Hyderabad,Not disclosed,Head-corporate Python Trainer,https://www.naukri.com/job-listings-Head-corpo...
443,Data Scientist,30+ days ago,3-6 yrs,230119006195,"Hive, Pig, HBase, NoSQL, Cassandra, Data Scien...",Bengaluru,Not disclosed,Data Scientist,https://www.naukri.com/job-listings-Data-Scien...
444,Data Scientist - Process Excellence & Analytics,30+ days ago,2-4 yrs,220119900198,"Deep Learning, Data Science, Predictive Analyt...",Noida,Not disclosed,Data Scientist - Process Excellence & Analytics,https://www.naukri.com/job-listings-Data-Scien...
445,Software Engineer,30+ days ago,2-5 yrs,220119003375,"c, java, information retrieval, data science, ...",Hyderabad,Not disclosed,Software Engineer,https://www.naukri.com/job-listings-Software-E...
446,Lead Data Scientist,30+ days ago,7-12 yrs,211218007900,"Data Science, Machine Learning, Artificial Int...",Bengaluru(HSR Layout),Not disclosed,Lead Data Scientist,https://www.naukri.com/job-listings-Lead-Data-...
447,Data Scientist Consultant/ Specialist - Machin...,30+ days ago,5-7 yrs,210119901670,"R, Data Science, Machine Learning, SAS, Statis...",Bengaluru,Not disclosed,Data Scientist Consultant/ Specialist - Machin...,https://www.naukri.com/job-listings-Data-Scien...
448,Machine Learning Engineer - Python,30+ days ago,2-7 yrs,210119901581,"Data Science, Machine Learning, Python, Predic...",Bengaluru,Not disclosed,Machine Learning Engineer - Python,https://www.naukri.com/job-listings-Machine-Le...
449,Director - Engineering,30+ days ago,10-17 yrs,210119900559,"Data Science, MongoDB, SCALA, Machine Learning...",Bengaluru,Not disclosed,Director - Engineering,https://www.naukri.com/job-listings-Director-E...

# Scrapping OyoRooms

In [67]:
url='https://www.oyorooms.com/oyos-in-bangalore'
browser.get(url)

In [70]:
hotels=browser.find_elements_by_css_selector("div.ember-view.mdl-cell.mdl-cell--12-col.newHotelCard")
len(parents)

21

In [ ]:
browser=webdriver.Chrome('chromedriver.exe')
url='https://www.oyorooms.com/oyos-in-bangalore'
browser.get(url)

In [111]:
import pandas as pd
import time

hotel_list=pd.DataFrame()
while True: 
    hotels=browser.find_elements_by_css_selector("div.ember-view.mdl-cell.mdl-cell--12-col.newHotelCard")
    for hotel in hotels:
        try:
            hotel_name=hotel.find_element_by_css_selector('span.newHotelCard__hotelName').text
        except:
            hotel_name=None
        #print(hotel_name)
        try:
            hotel_locations=hotel.find_element_by_css_selector('span.newHotelCard__hotelAddress').text
        except:
            hotel_name=None
        #print(hotel_locations)
        try:
            hotel_rprice=hotel.find_element_by_css_selector('span.newHotelCard__revisedPricing').text
        except:
            hotel_rprice=None
        #print(hotel_rprice)
        try:
            hotel_discount=hotel.find_element_by_css_selector('div.newHotelCard__discount').text
        except:
            hotel_discount=None
        #print(hotel_discount)
        try:
            hotel_rating=hotel.find_element_by_css_selector('span.hotelRating__value.hotelRating__value--verygood').text
        except:
            hotel_rating=None
        #print(hotel_rating)
        try:
            hotel_no_of_rating=hotel.find_element_by_css_selector('div.hotelRating__count').text
        except:
            hotel_no_of_rating=None
        #print(hotel_no_of_rating)
        try:
            hotel_url=hotel.find_element_by_css_selector('img.carousal__image').get_attribute('src')
        except:
            hotel_url=None
        #print(hotel_url)
        curr_row={'Hotel Name:':hotel_name,'Hotel Locations:':hotel_locations,"Hotel Revised Price:":hotel_rprice,
                  "Hotel Discount:":hotel_discount,"Hotel_Discount:":hotel_rating,"Number of ratings:":hotel_no_of_rating,
                  "Hotel link:":hotel_url}
        hotel_list=hotel_list.append(curr_row,ignore_index=True)
hotel_list    
#hotel_list.to_csv('Hotels.csv')

WebDriverException: Message: chrome not reachable
  (Session info: chrome=72.0.3626.119)
  (Driver info: chromedriver=73.0.3683.20 (8e2b610813e167eee3619ac4ce6e42e3ec622017),platform=Windows NT 10.0.17134 x86_64)

# Browsing through pages

In [132]:
browser=webdriver.Chrome('chromedriver.exe')
url='https://www.naukri.com/datascience-jobs'
browser.get(url)

In [114]:
browser.find_element_by_css_selector('button.grayBtn').click()

In [133]:
url='https://www.naukri.com/datascience-jobs'
def get_attribute(parent,selector,attribute):
    try:
        if attribute=='text':
            return parent.find_element_by_css_selector(selector).text
        else:
            return parent.find_element_by_css_selector(selector).get_attribute(attribute)
    except:
        val=None
    return val
jobs_df=pd.DataFrame()
while True:
    parents=browser.find_elements_by_css_selector('div.row[type="tuple"]') 
    for job in parents:
        job_id=job.get_attribute('id')
        url=job.get_attribute('data-url')
        title=get_attribute(job,'li.desig','title')
        company=get_attribute(job,'li.desig','title')
        exp=get_attribute(job,'span.exp','text')
        loc=get_attribute(job,'span.loc','text')
        key_skills=get_attribute(job,'span.skill','text')
        sal=get_attribute(job,'span.salary','text')
        date=get_attribute(job,'span.date','text')
        curr_row={'Url':url,'Job_ID':job_id,'Title':title,'Company':company,'Experience':exp,'Location':loc,'Key':key_skills,
                  'Salary':sal,'Date':date}
        jobs_df=jobs_df.append(curr_row,ignore_index=True)
        print(jobs_df.shape)
    try:
        button=browser.find_elements_by_css_selector('button.grayBtn')[-1]
        if button.text=='Next':
            button.click()
        else:
            break
        time.sleep(2)
    except Exception as e:
        print(e)
        break

(1, 9)
(2, 9)
(3, 9)
(4, 9)
(5, 9)
(6, 9)
(7, 9)
(8, 9)
(9, 9)
(10, 9)
(11, 9)
(12, 9)
(13, 9)
(14, 9)
(15, 9)
(16, 9)
(17, 9)
(18, 9)
(19, 9)
(20, 9)
(21, 9)
(22, 9)
(23, 9)
(24, 9)
(25, 9)
(26, 9)
(27, 9)
(28, 9)
(29, 9)
(30, 9)
(31, 9)
(32, 9)
(33, 9)
(34, 9)
(35, 9)
(36, 9)
(37, 9)
(38, 9)
(39, 9)
(40, 9)
(41, 9)
(42, 9)
(43, 9)
(44, 9)
(45, 9)
(46, 9)
(47, 9)
(48, 9)
(49, 9)
(50, 9)
(51, 9)
(52, 9)
(53, 9)
(54, 9)
(55, 9)
(56, 9)
(57, 9)
(58, 9)
(59, 9)
(60, 9)
(61, 9)
(62, 9)
(63, 9)
(64, 9)
(65, 9)
(66, 9)
(67, 9)
(68, 9)
(69, 9)
(70, 9)
(71, 9)
(72, 9)
(73, 9)
(74, 9)
(75, 9)
(76, 9)
(77, 9)
(78, 9)
(79, 9)
(80, 9)
(81, 9)
(82, 9)
(83, 9)
(84, 9)
(85, 9)
(86, 9)
(87, 9)
(88, 9)
(89, 9)
(90, 9)
(91, 9)
(92, 9)
(93, 9)
(94, 9)
(95, 9)
(96, 9)
(97, 9)
(98, 9)
(99, 9)
(100, 9)
(101, 9)
(102, 9)
(103, 9)
(104, 9)
(105, 9)
(106, 9)
(107, 9)
(108, 9)
(109, 9)
(110, 9)
(111, 9)
(112, 9)
(113, 9)
(114, 9)
(115, 9)
(116, 9)
(117, 9)
(118, 9)
(119, 9)
(120, 9)
(121, 9)
(122, 9)
(123, 9)
(124, 9)
(125, 9)
(126, 9)
(127, 9)
(128, 9)
(129, 9)
(130, 9)
(131, 9)
(132, 9)
(133, 9)
(134, 9)
(135, 9)
(136, 9)
(137, 9)
(138, 9)
(139, 9)
(140, 9)
(141, 9)
(142, 9)
(143, 9)
(144, 9)
(145, 9)
(146, 9)
(147, 9)
(148, 9)
(149, 9)
(150, 9)
(151, 9)
(152, 9)
(153, 9)
(154, 9)
(155, 9)
(156, 9)
(157, 9)
(158, 9)
(159, 9)
(160, 9)
(161, 9)
(162, 9)
(163, 9)
(164, 9)
(165, 9)
(166, 9)
(167, 9)
(168, 9)
(169, 9)
(170, 9)
(171, 9)
(172, 9)
(173, 9)
(174, 9)
(175, 9)
(176, 9)
(177, 9)
(178, 9)
(179, 9)
(180, 9)
(181, 9)
(182, 9)
(183, 9)
(184, 9)
(185, 9)
(186, 9)
(187, 9)
(188, 9)
(189, 9)
(190, 9)
(191, 9)
(192, 9)
(193, 9)
(194, 9)
(195, 9)
(196, 9)
(197, 9)
(198, 9)
(199, 9)
(200, 9)
(201, 9)
(202, 9)
(203, 9)
(204, 9)
(205, 9)
(206, 9)
(207, 9)
(208, 9)
(209, 9)
(210, 9)
(211, 9)
(212, 9)
(213, 9)
(214, 9)
(215, 9)
(216, 9)
(217, 9)
(218, 9)
(219, 9)
(220, 9)
(221, 9)
(222, 9)
(223, 9)
(224, 9)
(225, 9)
(226, 9)
(227, 9)
(228, 9)
(229, 9)
(230, 9)
(231, 9)
(232, 9)
(233, 9)
(234, 9)
(235, 9)
(236, 9)
(237, 9)
(238, 9)
(239, 9)
(240, 9)
(241, 9)
(242, 9)
(243, 9)
(244, 9)
(245, 9)
(246, 9)
(247, 9)
(248, 9)
(249, 9)
(250, 9)
(251, 9)
(252, 9)
(253, 9)
(254, 9)
(255, 9)
(256, 9)
(257, 9)
(258, 9)
(259, 9)
(260, 9)
(261, 9)
(262, 9)
(263, 9)
(264, 9)
(265, 9)
(266, 9)
(267, 9)
(268, 9)
(269, 9)
(270, 9)
(271, 9)
(272, 9)
(273, 9)
(274, 9)
(275, 9)
(276, 9)
(277, 9)
(278, 9)
(279, 9)
(280, 9)
(281, 9)
(282, 9)
(283, 9)
(284, 9)
(285, 9)
(286, 9)
(287, 9)
(288, 9)
(289, 9)
(290, 9)
(291, 9)
(292, 9)
(293, 9)
(294, 9)
(295, 9)
(296, 9)
(297, 9)
(298, 9)
(299, 9)
(300, 9)
(301, 9)
(302, 9)
(303, 9)
(304, 9)
(305, 9)
(306, 9)
(307, 9)
(308, 9)
(309, 9)
(310, 9)
(311, 9)
(312, 9)
(313, 9)
(314, 9)
(315, 9)
(316, 9)
(317, 9)
(318, 9)
(319, 9)
(320, 9)
(321, 9)
(322, 9)
(323, 9)
(324, 9)
(325, 9)
(326, 9)
(327, 9)
(328, 9)
(329, 9)
(330, 9)
(331, 9)
(332, 9)
(333, 9)
(334, 9)
(335, 9)
(336, 9)
(337, 9)
(338, 9)
(339, 9)
(340, 9)
(341, 9)
(342, 9)
(343, 9)
(344, 9)
(345, 9)
(346, 9)
(347, 9)
(348, 9)
(349, 9)
(350, 9)
(351, 9)
(352, 9)
(353, 9)
(354, 9)
(355, 9)
(356, 9)
(357, 9)
(358, 9)
(359, 9)
(360, 9)
(361, 9)
(362, 9)
(363, 9)
(364, 9)
(365, 9)
(366, 9)
(367, 9)
(368, 9)
(369, 9)
(370, 9)
(371, 9)
(372, 9)
(373, 9)
(374, 9)
(375, 9)
(376, 9)
(377, 9)
(378, 9)
(379, 9)
(380, 9)
(381, 9)
(382, 9)
(383, 9)
(384, 9)
(385, 9)
(386, 9)
(387, 9)
(388, 9)
(389, 9)
(390, 9)
(391, 9)
(392, 9)
(393, 9)
(394, 9)
(395, 9)
(396, 9)
(397, 9)
(398, 9)
(399, 9)
(400, 9)
(401, 9)
(402, 9)
(403, 9)
(404, 9)
(405, 9)
(406, 9)
(407, 9)
(408, 9)
(409, 9)
(410, 9)
(411, 9)
(412, 9)
(413, 9)
(414, 9)
(415, 9)
(416, 9)
(417, 9)
(418, 9)
(419, 9)
(420, 9)
(421, 9)
(422, 9)
(423, 9)
(424, 9)
(425, 9)
(426, 9)
(427, 9)
(428, 9)
(429, 9)
(430, 9)
(431, 9)
(432, 9)
(433, 9)
(434, 9)
(435, 9)
(436, 9)
(437, 9)
(438, 9)
(439, 9)
(440, 9)
(441, 9)
(442, 9)
(443, 9)
(444, 9)
(445, 9)
(446, 9)
(447, 9)
(448, 9)
(449, 9)
(450, 9)
(451, 9)
(452, 9)
(453, 9)
(454, 9)
(455, 9)
(456, 9)
(457, 9)
(458, 9)
(459, 9)
(460, 9)
(461, 9)
(462, 9)
(463, 9)
(464, 9)
(465, 9)
(466, 9)
(467, 9)
(468, 9)
(469, 9)
(470, 9)
(471, 9)
(472, 9)
(473, 9)
(474, 9)
(475, 9)
(476, 9)
(477, 9)
(478, 9)
(479, 9)
(480, 9)
(481, 9)
(482, 9)
(483, 9)
(484, 9)
(485, 9)
(486, 9)
(487, 9)
(488, 9)
(489, 9)
(490, 9)
(491, 9)
(492, 9)
(493, 9)
(494, 9)
(495, 9)
(496, 9)
(497, 9)
(498, 9)
(499, 9)
(500, 9)
(501, 9)
(502, 9)
(503, 9)
(504, 9)
(505, 9)
(506, 9)
(507, 9)
(508, 9)
(509, 9)
(510, 9)
(511, 9)
(512, 9)
(513, 9)
(514, 9)
(515, 9)
(516, 9)
(517, 9)
(518, 9)
(519, 9)
(520, 9)
(521, 9)
(522, 9)
(523, 9)
(524, 9)
(525, 9)
(526, 9)
(527, 9)
(528, 9)
(529, 9)
(530, 9)
(531, 9)
(532, 9)
(533, 9)
(534, 9)
(535, 9)
(536, 9)
(537, 9)
(538, 9)
(539, 9)
(540, 9)
(541, 9)
(542, 9)
(543, 9)
(544, 9)
(545, 9)
(546, 9)
(547, 9)
(548, 9)
(549, 9)
(550, 9)
(551, 9)
(552, 9)
(553, 9)
(554, 9)
(555, 9)
(556, 9)
(557, 9)
(558, 9)
(559, 9)
(560, 9)
(561, 9)
(562, 9)
(563, 9)
(564, 9)
(565, 9)
(566, 9)
(567, 9)
(568, 9)
(569, 9)
(570, 9)
(571, 9)
(572, 9)
(573, 9)
(574, 9)
(575, 9)
(576, 9)
(577, 9)
(578, 9)
(579, 9)
(580, 9)
(581, 9)
(582, 9)
(583, 9)
(584, 9)
(585, 9)
(586, 9)
(587, 9)
(588, 9)
(589, 9)
(590, 9)
(591, 9)
(592, 9)
(593, 9)
(594, 9)
(595, 9)
(596, 9)
(597, 9)
(598, 9)
(599, 9)
(600, 9)
(601, 9)
(602, 9)
(603, 9)
(604, 9)
(605, 9)
(606, 9)
(607, 9)
(608, 9)
(609, 9)
(610, 9)
(611, 9)
(612, 9)
(613, 9)
(614, 9)
(615, 9)
(616, 9)
(617, 9)
(618, 9)
(619, 9)
(620, 9)
(621, 9)
(622, 9)
(623, 9)
(624, 9)
(625, 9)
(626, 9)
(627, 9)
(628, 9)
(629, 9)
(630, 9)
(631, 9)
(632, 9)
(633, 9)
(634, 9)
(635, 9)
(636, 9)
(637, 9)
(638, 9)
(639, 9)
(640, 9)
(641, 9)
(642, 9)
(643, 9)
(644, 9)
(645, 9)
(646, 9)
(647, 9)
(648, 9)
(649, 9)
(650, 9)
(651, 9)
(652, 9)
(653, 9)
(654, 9)
(655, 9)
(656, 9)
(657, 9)
(658, 9)
(659, 9)
(660, 9)
(661, 9)
(662, 9)
(663, 9)
(664, 9)
(665, 9)
(666, 9)
(667, 9)
(668, 9)
(669, 9)
(670, 9)
(671, 9)
(672, 9)
(673, 9)
(674, 9)
(675, 9)
(676, 9)
(677, 9)
(678, 9)
(679, 9)
(680, 9)
(681, 9)
(682, 9)
(683, 9)
(684, 9)
(685, 9)
(686, 9)
(687, 9)
(688, 9)
(689, 9)
(690, 9)
(691, 9)
(692, 9)
(693, 9)
(694, 9)
(695, 9)
(696, 9)
(697, 9)
(698, 9)
(699, 9)
(700, 9)
(701, 9)
(702, 9)
(703, 9)
(704, 9)
(705, 9)
(706, 9)
(707, 9)
(708, 9)
(709, 9)
(710, 9)
(711, 9)
(712, 9)
(713, 9)
(714, 9)
(715, 9)
(716, 9)
(717, 9)
(718, 9)
(719, 9)
(720, 9)
(721, 9)
(722, 9)
(723, 9)
(724, 9)
(725, 9)
(726, 9)
(727, 9)
(728, 9)
(729, 9)
(730, 9)
(731, 9)
(732, 9)
(733, 9)
(734, 9)
(735, 9)
(736, 9)
(737, 9)
(738, 9)
(739, 9)
(740, 9)
(741, 9)
(742, 9)
(743, 9)
(744, 9)
(745, 9)
(746, 9)
(747, 9)
(748, 9)
(749, 9)
(750, 9)
(751, 9)
(752, 9)
(753, 9)
(754, 9)
(755, 9)
(756, 9)
(757, 9)
(758, 9)
(759, 9)
(760, 9)
(761, 9)
(762, 9)
(763, 9)
(764, 9)
(765, 9)
(766, 9)
(767, 9)
(768, 9)
(769, 9)
(770, 9)
(771, 9)
(772, 9)
(773, 9)
(774, 9)
(775, 9)
(776, 9)
(777, 9)
(778, 9)
(779, 9)
(780, 9)
(781, 9)
(782, 9)
(783, 9)
(784, 9)
(785, 9)
(786, 9)
(787, 9)
(788, 9)
(789, 9)
(790, 9)
(791, 9)
(792, 9)
(793, 9)
(794, 9)
(795, 9)
(796, 9)
(797, 9)
(798, 9)
(799, 9)
(800, 9)
(801, 9)
(802, 9)
(803, 9)
(804, 9)
(805, 9)
(806, 9)
(807, 9)
(808, 9)
(809, 9)
(810, 9)
(811, 9)
(812, 9)
(813, 9)
(814, 9)
(815, 9)
(816, 9)
(817, 9)
(818, 9)
(819, 9)
(820, 9)
(821, 9)
(822, 9)
(823, 9)
(824, 9)
(825, 9)
(826, 9)
(827, 9)
(828, 9)
(829, 9)
(830, 9)
(831, 9)
(832, 9)
(833, 9)
(834, 9)
(835, 9)
(836, 9)
(837, 9)
(838, 9)
(839, 9)
(840, 9)
(841, 9)
(842, 9)
(843, 9)
(844, 9)
(845, 9)
(846, 9)
(847, 9)
(848, 9)
(849, 9)
(850, 9)
(851, 9)
(852, 9)
(853, 9)
(854, 9)
(855, 9)
(856, 9)
(857, 9)
(858, 9)
(859, 9)
(860, 9)
(861, 9)
(862, 9)
(863, 9)
(864, 9)
(865, 9)
(866, 9)
(867, 9)
(868, 9)
(869, 9)
(870, 9)
(871, 9)
(872, 9)
(873, 9)
(874, 9)
(875, 9)
(876, 9)
(877, 9)
(878, 9)
(879, 9)
(880, 9)
(881, 9)
(882, 9)
(883, 9)
(884, 9)
(885, 9)
(886, 9)
(887, 9)
(888, 9)
(889, 9)
(890, 9)
(891, 9)
(892, 9)
(893, 9)
(894, 9)
(895, 9)
(896, 9)
(897, 9)
(898, 9)
(899, 9)
(900, 9)
(901, 9)
(902, 9)
(903, 9)
(904, 9)
(905, 9)
(906, 9)
(907, 9)
(908, 9)
(909, 9)
(910, 9)
(911, 9)
(912, 9)
(913, 9)
(914, 9)
(915, 9)
(916, 9)
(917, 9)
(918, 9)
(919, 9)
(920, 9)
(921, 9)
(922, 9)
(923, 9)
(924, 9)

(925, 9)
(926, 9)
(927, 9)
(928, 9)
(929, 9)
(930, 9)
(931, 9)
(932, 9)
(933, 9)
(934, 9)
(935, 9)
(936, 9)
(937, 9)
(938, 9)
(939, 9)
(940, 9)
(941, 9)
(942, 9)
(943, 9)
(944, 9)
(945, 9)
(946, 9)
(947, 9)
(948, 9)
(949, 9)
(950, 9)
(951, 9)
(952, 9)
(953, 9)
(954, 9)
(955, 9)
(956, 9)
(957, 9)
(958, 9)
(959, 9)
(960, 9)
(961, 9)
(962, 9)
(963, 9)
(964, 9)
(965, 9)
(966, 9)
(967, 9)
(968, 9)
(969, 9)
(970, 9)
(971, 9)
(972, 9)
(973, 9)
(974, 9)
(975, 9)
(976, 9)
(977, 9)
(978, 9)
(979, 9)
(980, 9)
(981, 9)
(982, 9)
(983, 9)
(984, 9)
(985, 9)
(986, 9)
(987, 9)
(988, 9)
(989, 9)
(990, 9)
(991, 9)
(992, 9)
(993, 9)
(994, 9)
(995, 9)
(996, 9)
(997, 9)
(998, 9)
(999, 9)
(1000, 9)
(1001, 9)
(1002, 9)
(1003, 9)
(1004, 9)
(1005, 9)
(1006, 9)
(1007, 9)
(1008, 9)
(1009, 9)
(1010, 9)
(1011, 9)
(1012, 9)
(1013, 9)
(1014, 9)
(1015, 9)
(1016, 9)
(1017, 9)
(1018, 9)
(1019, 9)
(1020, 9)
(1021, 9)
(1022, 9)
(1023, 9)
(1024, 9)
(1025, 9)
(1026, 9)
(1027, 9)
(1028, 9)
(1029, 9)
(1030, 9)
(1031, 9)
(1032, 9)
(1033, 9)
(1034, 9)
(1035, 9)
(1036, 9)
(1037, 9)
(1038, 9)
(1039, 9)
(1040, 9)
(1041, 9)
(1042, 9)
(1043, 9)
(1044, 9)
(1045, 9)
(1046, 9)
(1047, 9)
(1048, 9)
(1049, 9)
(1050, 9)
(1051, 9)
(1052, 9)
(1053, 9)
(1054, 9)
(1055, 9)
(1056, 9)
(1057, 9)
(1058, 9)
(1059, 9)
(1060, 9)
(1061, 9)
(1062, 9)
(1063, 9)
(1064, 9)
(1065, 9)
(1066, 9)
(1067, 9)
(1068, 9)
(1069, 9)
(1070, 9)
(1071, 9)
(1072, 9)
(1073, 9)
(1074, 9)
(1075, 9)
(1076, 9)
(1077, 9)
(1078, 9)
(1079, 9)
(1080, 9)
(1081, 9)
(1082, 9)
(1083, 9)
(1084, 9)
(1085, 9)
(1086, 9)
(1087, 9)
(1088, 9)
(1089, 9)
(1090, 9)
(1091, 9)
(1092, 9)
(1093, 9)
(1094, 9)
(1095, 9)
(1096, 9)
(1097, 9)
(1098, 9)
(1099, 9)
(1100, 9)
(1101, 9)
(1102, 9)
(1103, 9)
(1104, 9)
(1105, 9)
(1106, 9)
(1107, 9)
(1108, 9)
(1109, 9)
(1110, 9)
(1111, 9)
(1112, 9)
(1113, 9)
(1114, 9)
(1115, 9)
(1116, 9)
(1117, 9)
(1118, 9)
(1119, 9)
(1120, 9)
(1121, 9)
(1122, 9)
(1123, 9)
(1124, 9)
(1125, 9)
(1126, 9)
(1127, 9)
(1128, 9)
(1129, 9)
(1130, 9)
(1131, 9)
(1132, 9)
(1133, 9)
(1134, 9)
(1135, 9)
(1136, 9)
(1137, 9)
(1138, 9)
(1139, 9)
(1140, 9)
(1141, 9)
(1142, 9)
(1143, 9)
(1144, 9)
(1145, 9)
(1146, 9)
(1147, 9)
(1148, 9)
(1149, 9)
(1150, 9)
(1151, 9)
(1152, 9)
(1153, 9)
(1154, 9)
(1155, 9)
(1156, 9)
(1157, 9)
(1158, 9)
(1159, 9)
(1160, 9)
(1161, 9)
(1162, 9)
(1163, 9)
(1164, 9)
(1165, 9)
(1166, 9)
(1167, 9)
(1168, 9)
(1169, 9)
(1170, 9)
(1171, 9)
(1172, 9)
(1173, 9)
(1174, 9)
(1175, 9)
(1176, 9)
(1177, 9)
(1178, 9)
(1179, 9)
(1180, 9)
(1181, 9)
(1182, 9)
(1183, 9)
(1184, 9)
(1185, 9)
(1186, 9)
(1187, 9)
(1188, 9)
(1189, 9)
(1190, 9)
(1191, 9)
(1192, 9)
(1193, 9)
(1194, 9)
(1195, 9)
(1196, 9)
(1197, 9)
(1198, 9)

KeyboardInterrupt:

In [5]:
import pandas as pd
import time
browser=webdriver.Chrome('chromedriver.exe')
url='https://www.oyorooms.com/oyos-in-bangalore'
browser.get(url)
hotel_list=pd.DataFrame()
while True: 
    hotels=browser.find_elements_by_css_selector("div.ember-view.mdl-cell.mdl-cell--12-col.newHotelCard")
    for hotel in hotels:
        try:
            hotel_name=hotel.find_element_by_css_selector('span.newHotelCard__hotelName').text
        except:
            hotel_name=None
        try:
            hotel_locations=hotel.find_element_by_css_selector('span.newHotelCard__hotelAddress').text
        except:
            hotel_name=None
        try:
            hotel_rprice=hotel.find_element_by_css_selector('span.newHotelCard__revisedPricing').text
        except:
            hotel_rprice=None
        try:
            hotel_discount=hotel.find_element_by_css_selector('div.newHotelCard__discount').text
        except:
            hotel_discount=None
        try:
            hotel_rating=hotel.find_element_by_css_selector('span.hotelRating__value.hotelRating__value--verygood').text
        except:
            hotel_rating=None
        try:
            hotel_no_of_rating=hotel.find_element_by_css_selector('div.hotelRating__count').text
        except:
            hotel_no_of_rating=None
        try:
            hotel_url=hotel.find_element_by_css_selector('img.carousal__image').get_attribute('src')
        except:
            hotel_url=None
        curr_row={'Hotel Name:':hotel_name,'Hotel Locations:':hotel_locations,"Hotel Revised Price:":hotel_rprice,
                  "Hotel Discount:":hotel_discount,"Hotel_Discount:":hotel_rating,"Number of ratings:":hotel_no_of_rating,
                  "Hotel link:":hotel_url}
        hotel_list=hotel_list.append(curr_row,ignore_index=True)
        try:
            button=browser.find_element_by_css_selector('div.btn.btn-next[data-ember-action]')
            if button.text=='Next':
                button.click()
            else:
                break
        except Exception as e:
            print(e)
            break
        time.sleep(2)
hotel_list

Message: chrome not reachable
  (Session info: chrome=72.0.3626.121)
  (Driver info: chromedriver=73.0.3683.20 (8e2b610813e167eee3619ac4ce6e42e3ec622017),platform=Windows NT 10.0.17134 x86_64)

WebDriverException: Message: chrome not reachable
  (Session info: chrome=72.0.3626.121)
  (Driver info: chromedriver=73.0.3683.20 (8e2b610813e167eee3619ac4ce6e42e3ec622017),platform=Windows NT 10.0.17134 x86_64)